document:
  name: Linee guida per l’armonizzazione delle qualificazioni professionali, delle professioni e dei profili in ambito ICT
  description: |
    Con le Linee guida per l’armonizzazione delle qualificazioni professionali,
    delle professioni e dei profili in ambito ICT, AGID mette a disposizione di
    Regioni, enti titolati e amministrazioni, uno strumento utile a comprendere
    la necessità di armonizzare le terminologie utilizzate (ad esempio nei
    repertori regionali), allineandosi ove possibile ai profili ICT nazionali
    recepiti nelle linee guida AGID.
  tags:
    - competenze digitali
    - linee guida